// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-ufczM9nSzz48cCZ1ciuJyOh2Cck5k0',
    appId: '1:593726978561:web:d815b6fd53124510bf9e00',
    messagingSenderId: '593726978561',
    projectId: 'e-commerce-d24b7',
    authDomain: 'e-commerce-d24b7.firebaseapp.com',
    storageBucket: 'e-commerce-d24b7.appspot.com',
    measurementId: 'G-SH9BVN73EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBScx94QxZOhJVgxJGlHsD_VxigvbQVsa8',
    appId: '1:593726978561:android:d672f2444bdaa048bf9e00',
    messagingSenderId: '593726978561',
    projectId: 'e-commerce-d24b7',
    storageBucket: 'e-commerce-d24b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBReDQ6ZRADjgH2nTq1FuKx3nMjJHkR8Ss',
    appId: '1:593726978561:ios:e62340578e5187a2bf9e00',
    messagingSenderId: '593726978561',
    projectId: 'e-commerce-d24b7',
    storageBucket: 'e-commerce-d24b7.appspot.com',
    iosClientId: '593726978561-ds9rqdmh75bidtq6u7b83et3ast2clrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBReDQ6ZRADjgH2nTq1FuKx3nMjJHkR8Ss',
    appId: '1:593726978561:ios:e62340578e5187a2bf9e00',
    messagingSenderId: '593726978561',
    projectId: 'e-commerce-d24b7',
    storageBucket: 'e-commerce-d24b7.appspot.com',
    iosClientId: '593726978561-ds9rqdmh75bidtq6u7b83et3ast2clrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientecommerce',
  );
}
